# Multipass, Nukkit permission system
#
general:
# Messages language
  language: default
# Save translation file
  language-save: false
# Show debug info (it will spam a lot in a server console :))
  debug: false
permissions:
  subgroup:
# Default subgroup. All players will automagically join this subgroup
    default-subgroup: default
# Default priority of subgroup permissions
    default-priority: 10
  user:
# Default priority of user permissions
    default-priority: 100
  multiworld:
# Enable (true) multiworld permisions support
    enable: false
# Configure world permission mirrors
    mirrors:
      world: nether_world, end_world